// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jolxnjczfnufqpvhbhdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbHhuamN6Zm51ZnFwdmhiaGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDkxMjEsImV4cCI6MjA3MTQyNTEyMX0.FlgNYhsZUV-hI8Q_U7NORCnUeS0Uy6Hte4Z2aBLcgdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});